Only continue upload step if the PR was merged.
If it wasn't merged, fail with an error message.

diff --git a/.github/workflows/ansible-release.yml b/.github/workflows/ansible-release.yml
--- a/.github/workflows/ansible-release.yml
+++ b/.github/workflows/ansible-release.yml
@@ -23,6 +23,8 @@ jobs:
     permissions:
       pull-requests: write
       contents: write
+    outputs:
+      pr_url: ${{ steps.create-pr.outputs.pr_url }}
 
     steps:
       - name: Check out antsibull
@@ -91,17 +93,19 @@ jobs:
          git push origin "publish-${ANSIBLE_VERSION}"
 
       - name: Create PR to the ansible-build-data
+        id: create-pr
         working-directory: antsibull/build/ansible-build-data
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           ARTIFACT_URL: ${{ steps.upload-artifact.outputs.artifact-url }}
         run: |
           body="$(echo -e "${CI_COMMIT_MESSAGE}\nRelease artifacts: <${ARTIFACT_URL}>")"
+          echo -n "pr_url=" >> "$GITHUB_OUTPUT"
           gh pr create \
           --base main \
           --head "publish-${ANSIBLE_VERSION}" \
           --title "Release Ansible ${ANSIBLE_VERSION}" \
-          --body "${body}"
+          --body "${body}" >> "$GITHUB_OUTPUT"
 
   # publish job downloads the arifacts and publish it to PyPI
 
@@ -116,6 +120,16 @@ jobs:
       id-token: write
 
     steps:
+
+    - name: Ensure that the PR was merged
+      env:
+        PR_URL: ${{ needs.build.outputs.create-pr }}
+      run: |
+        STATE=$(gh pr view "${PR_URL}" --json state --template "{{.state}}")
+        if [ "${STATE}" != "MERGED" ]; then
+          echo "::error ::The state of PR ${PR_URL} must be MERGED, not ${STATE}"
+          exit 1
+        fi
 
     - name: Download artifact
       uses: actions/download-artifact@v4
